name: Gatsby garden get

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  repository_dispatch:
    types: [update_zettelkasten]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Manual build'
        default: 'World'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install --legacy-peer-deps
      - run: npm run build

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GATSBY_ZEN_SECRET }}
          deploy-branch: gh-pages
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
          cname: 'https://omegakid1902.github.io/gatsby-zen-garden/'

